# Generated by Django 6.0.3 on 2026-03-26 21:12

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_LEVELS = [
    ('budget', 'Бюджетный', 'bg-success', 0),
    ('mid',    'Средний',   'bg-info',    1),
    ('high',   'Высокий',   'bg-warning', 2),
    ('ultra',  'Топовый',   'bg-danger',  3),
]


def create_levels_and_migrate(apps, schema_editor):
    PrebuiltLevel = apps.get_model('store', 'PrebuiltLevel')
    PrebuiltPC = apps.get_model('store', 'PrebuiltPC')

    # Создаём уровни и запоминаем маппинг старый slug -> объект
    level_map = {}
    for slug, name, color, order in DEFAULT_LEVELS:
        obj = PrebuiltLevel.objects.create(name=name, color=color, order=order)
        level_map[slug] = obj

    # Переносим старые значения на новые объекты
    for pc in PrebuiltPC.objects.all():
        old_val = pc.level  # строка ('budget', 'mid', ...)
        new_level = level_map.get(old_val)
        pc.level = str(new_level.pk) if new_level else None
        pc.save(update_fields=['level'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuiltLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(default='bg-secondary', help_text='Например: bg-success, bg-info, bg-warning, bg-danger', max_length=50, verbose_name='Цвет бейджа (Bootstrap)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Уровень сборки',
                'verbose_name_plural': 'Уровни сборок',
                'ordering': ['order'],
            },
        ),
        # Сначала делаем поле nullable со строковым типом для совместимости
        migrations.AlterField(
            model_name='prebuiltpc',
            name='level',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        # Переносим данные
        migrations.RunPython(create_levels_and_migrate, reverse_migration),
        # Меняем на ForeignKey
        migrations.AlterField(
            model_name='prebuiltpc',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.prebuiltlevel', verbose_name='Уровень'),
        ),
    ]
