# Generated by Django 6.0.3 on 2026-03-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_prebuiltlevel_alter_prebuiltpc_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, choices=[('', 'Не применимо'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], help_text='Тип RAM (для MB и RAM-планок)', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='socket',
            field=models.CharField(blank=True, choices=[('', 'Не применимо'), ('AM1', 'AMD AM1'), ('AM2', 'AMD AM2'), ('AM2+', 'AMD AM2+'), ('AM3', 'AMD AM3'), ('AM3+', 'AMD AM3+'), ('AM4', 'AMD AM4'), ('AM5', 'AMD AM5'), ('FM1', 'AMD FM1'), ('FM2', 'AMD FM2'), ('FM2+', 'AMD FM2+'), ('SP3', 'AMD SP3 (EPYC)'), ('SP5', 'AMD SP5 (EPYC)'), ('TR4', 'AMD TR4 (Threadripper)'), ('TRX40', 'AMD TRX40 (Threadripper)'), ('TRX50', 'AMD TRX50 (Threadripper)'), ('LGA775', 'Intel LGA775'), ('LGA1150', 'Intel LGA1150'), ('LGA1151', 'Intel LGA1151'), ('LGA1155', 'Intel LGA1155'), ('LGA1156', 'Intel LGA1156'), ('LGA1200', 'Intel LGA1200'), ('LGA1700', 'Intel LGA1700'), ('LGA1851', 'Intel LGA1851'), ('LGA2011', 'Intel LGA2011'), ('LGA2011-3', 'Intel LGA2011-3'), ('LGA2066', 'Intel LGA2066 (HEDT)'), ('LGA4189', 'Intel LGA4189 (Xeon)'), ('LGA4677', 'Intel LGA4677 (Xeon)')], help_text='Для совместимости CPU/MB', max_length=50),
        ),
    ]
