# Generated by Django 6.0.3 on 2026-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_ram_type_alter_product_socket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='Страница')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User Agent')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Статистика посещений',
                'ordering': ['-created_at'],
            },
        ),
    ]
